import { useState } from 'react'
import { Coins, ArrowRight } from '@phosphor-icons/react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { toast } from 'sonner'

interface InviteVerificationProps {
  onVerified: (code: string) => void
}

export function InviteVerification({ onVerified }: InviteVerificationProps) {
  const [code, setCode] = useState('')
  const [isVerifying, setIsVerifying] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (code.length < 8) {
      toast.error('Please enter a valid invite code')
      return
    }

    setIsVerifying(true)
    
    setTimeout(() => {
      const isValid = true
      
      if (isValid) {
        toast.success('Welcome to the neighborhood!')
        onVerified(code)
      } else {
        toast.error('Invalid invite code. Please try again.')
        setIsVerifying(false)
      }
    }, 1000)
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-background px-6">
      <div className="w-full max-w-md space-y-8">
        <div className="flex flex-col items-center text-center space-y-4">
          <Coins 
            size={64} 
            weight="duotone" 
            className="text-primary lantern-glow" 
          />
          <div>
            <h1 className="text-3xl font-semibold text-foreground mb-2">
              Join the Neighborhood
            </h1>
            <p className="text-muted-foreground">
              Enter your invite code to get started
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="invite-code">Invite Code</Label>
            <Input
              id="invite-code"
              placeholder="ABCD-1234"
              value={code}
              onChange={(e) => setCode(e.target.value.toUpperCase())}
              maxLength={9}
              className="text-center text-lg tracking-wider"
              autoFocus
            />
          </div>

          <Button 
            type="submit" 
            className="w-full" 
            size="lg"
            disabled={isVerifying || code.length < 8}
          >
            {isVerifying ? 'Verifying...' : 'Continue'}
            {!isVerifying && <ArrowRight className="ml-2" size={20} />}
          </Button>
        </form>

        <p className="text-xs text-center text-muted-foreground">
          Invite codes are generated by Elder members of the community.
          Ask a neighbor for theirs!
        </p>
      </div>
    </div>
  )
}
